/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import keeptoo.Drag;

/**
 *
 * @author ckinateder
 */
public class SourceEditor extends javax.swing.JFrame {

    /**
     * Creates new form SourceEditor
     */
    public SourceEditor() {
        initComponents();
        updateSrc();
        //scroller.sources = sources;
        //System.out.println(sources);
        scroller.setLabel(sourceslist);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new keeptoo.KGradientPanel();
        closelbl = new javax.swing.JLabel();
        loginbtn = new keeptoo.KButton();
        loginbtn1 = new keeptoo.KButton();
        keywordfield = new javax.swing.JTextField();
        sourceslist = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setShape(new RoundRectangle2D.Double(0, 0, 496, 334, 20, 20));

        LoginPanel.setBackground(new Color(0,0,0,0));
        LoginPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginPanel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        LoginPanel.setkBorderRadius(20);
        LoginPanel.setkEndColor(new java.awt.Color(51, 51, 140));
        LoginPanel.setkGradientFocus(250);
        LoginPanel.setkStartColor(new java.awt.Color(83, 97, 112));
        LoginPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                LoginPanelMouseDragged(evt);
            }
        });
        LoginPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LoginPanelMouseReleased(evt);
            }
        });
        LoginPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginPanelKeyPressed(evt);
            }
        });
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closelbl.setForeground(new java.awt.Color(255, 255, 255));
        closelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icons8-cancel-32.png"))); // NOI18N
        closelbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                closelblMouseDragged(evt);
            }
        });
        closelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closelblMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closelblMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closelblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closelblMouseEntered(evt);
            }
        });
        LoginPanel.add(closelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 30, 30));

        loginbtn.setText("Remove Source");
        loginbtn.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        loginbtn.setkAllowTab(false);
        loginbtn.setkBorderRadius(40);
        loginbtn.setkEndColor(new java.awt.Color(0, 204, 51));
        loginbtn.setkHoverEndColor(new java.awt.Color(78, 160, 143));
        loginbtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        loginbtn.setkHoverStartColor(new java.awt.Color(63, 167, 89));
        loginbtn.setkIndicatorThickness(0);
        loginbtn.setkPressedColor(new java.awt.Color(167, 69, 199));
        loginbtn.setkSelectedColor(new java.awt.Color(163, 62, 167));
        loginbtn.setName(""); // NOI18N
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginbtnMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtnMouseClicked(evt);
            }
        });
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        LoginPanel.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 150, 40));

        loginbtn1.setText("Add Source");
        loginbtn1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        loginbtn1.setkAllowTab(false);
        loginbtn1.setkBorderRadius(40);
        loginbtn1.setkEndColor(new java.awt.Color(0, 204, 51));
        loginbtn1.setkHoverEndColor(new java.awt.Color(78, 160, 143));
        loginbtn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        loginbtn1.setkHoverStartColor(new java.awt.Color(63, 167, 89));
        loginbtn1.setkIndicatorThickness(0);
        loginbtn1.setkPressedColor(new java.awt.Color(167, 69, 199));
        loginbtn1.setkSelectedColor(new java.awt.Color(163, 62, 167));
        loginbtn1.setName(""); // NOI18N
        loginbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginbtn1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginbtn1MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtn1MouseClicked(evt);
            }
        });
        loginbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtn1ActionPerformed(evt);
            }
        });
        LoginPanel.add(loginbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 150, 40));

        keywordfield.setBackground(new Color(0,0,0,0));
        keywordfield.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        keywordfield.setForeground(new java.awt.Color(255, 255, 255));
        keywordfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        keywordfield.setCaretColor(new java.awt.Color(255, 255, 255));
        keywordfield.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        keywordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordfieldActionPerformed(evt);
            }
        });
        LoginPanel.add(keywordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 350, 30));

        sourceslist.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        sourceslist.setForeground(new java.awt.Color(255, 255, 255));
        sourceslist.setText("Add a source");
        sourceslist.setToolTipText("scroll for all sources");
        sourceslist.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        sourceslist.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        sourceslist.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                sourceslistMouseWheelMoved(evt);
            }
        });
        LoginPanel.add(sourceslist, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 410, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closelblMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelblMouseDragged
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closelblMouseDragged

    private void closelblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelblMousePressed
        // TODO add your handling code here:
        //System.exit(0);
    }//GEN-LAST:event_closelblMousePressed

    private void closelblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelblMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_closelblMouseReleased

    private void closelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelblMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closelblMouseClicked

    private void closelblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelblMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_closelblMouseEntered

    private void loginbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_loginbtnMousePressed

    private void loginbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseReleased
        // TODO add your handling code here:
        //CreateAccountPanel.setVisible(false);
        //change to ref not val
        
    }//GEN-LAST:event_loginbtnMouseReleased

    private void loginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_loginbtnMouseClicked

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtnActionPerformed

    private void LoginPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPanelMouseDragged
        // TODO add your handling code here:
        //drag here
        new Drag(LoginPanel).moveWindow(evt);
    }//GEN-LAST:event_LoginPanelMouseDragged

    private void LoginPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPanelMousePressed
        // TODO add your handling code here:
        new Drag(LoginPanel).onPress(evt);
        //use mouse always
    }//GEN-LAST:event_LoginPanelMousePressed

    private void LoginPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginPanelMouseReleased

    private void LoginPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginPanelKeyPressed
        // TODO add your handling code here:
        //

    }//GEN-LAST:event_LoginPanelKeyPressed

    private void loginbtn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtn1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtn1MousePressed

    private void loginbtn1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtn1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtn1MouseReleased

    private void loginbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtn1MouseClicked

    private void loginbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtn1ActionPerformed

    private void keywordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordfieldActionPerformed

    private void sourceslistMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_sourceslistMouseWheelMoved
        // TODO add your handling code here:
        scroller.scrollSources(evt);
    }//GEN-LAST:event_sourceslistMouseWheelMoved
    ArrayList<Link> sources = new ArrayList<>();
    Scroller scroller = new Scroller(sources, 9);
    
    String sourcesFile = "sources.txt";
    public void updateSrc(){
        sources.clear();
        try {
            // FileReader reads text files in the default encoding.
            FileReader fileReader = 
                new FileReader(sourcesFile);
           
            BufferedReader bufferedReader = 
                new BufferedReader(fileReader);
            String line;
            while ((line = bufferedReader.readLine()) != null) {
                 sources.add(new Link(line));
            }            
            bufferedReader.close();         
        }
        catch(FileNotFoundException ex) {
            System.out.println(
                "Unable to open file '" + 
                sourcesFile + "'");
        }
        catch(IOException ex) {
            System.out.println(
                "Error reading file '" 
                + sourcesFile + "'");
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SourceEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SourceEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SourceEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SourceEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SourceEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel LoginPanel;
    private javax.swing.JLabel closelbl;
    private javax.swing.JTextField keywordfield;
    private keeptoo.KButton loginbtn;
    private keeptoo.KButton loginbtn1;
    private javax.swing.JLabel sourceslist;
    // End of variables declaration//GEN-END:variables
}
